// Generated by scripts/prepare_pack.py from the selected proxy coverage.
namespace ProxyExportBootstrap
{
    internal static class ProxyExportTargets
    {
        internal static readonly string[] Names = new string[]
        {
            "Zenitaia",
            "Relicta",
            "Kerbin - Water Mod Ready",
            "Aulden",
            "Terminus (Black Hole)",
        };
    }
}
