"""Derive the Phase A pack from the resolved Steam collection and local policy."""
import json, collections, xml.etree.ElementTree as ET
from pathlib import Path
from audit import ROOT, OUT, dump, scan

TITLES = {'2941085186':'Kerbin', '2961923776':'Aulden', '2961924256':'Seren'}
POLICY_FILE = ROOT / 'phase-a-pack-policy.json'
COLLECTION_REPORT = OUT / 'steam-collection.json'

def main():
    pool=json.loads((ROOT/'campaign-planets.json').read_text(encoding='utf-8'))
    policy=json.loads(POLICY_FILE.read_text(encoding='utf-8'))
    rsg_pool=ROOT/'mods/RandomSectorGenerator/Data/Scripts/RandomSectorGenerator/CampaignPlanetPool.cs'
    pool_source='// Generated by scripts/prepare_pack.py from campaign-planets.json.\nnamespace RandomSectorGenerator\n{\n    internal static class CampaignPlanetPool\n    {\n'
    for field,key in [('RequiredCustom','required_custom'),('Vanilla','vanilla'),('OptionalCustom','optional_custom')]:
        pool_source+='        internal static readonly string[] '+field+' = new string[]\n        {\n'
        pool_source+=''.join('            '+json.dumps(name)+',\n' for name in pool[key])
        pool_source+='        };\n'
    pool_source+='    }\n}\n'
    pool_bytes=pool_source.replace('\n','\r\n').encode('utf-8')
    if not rsg_pool.is_file() or rsg_pool.read_bytes()!=pool_bytes:
        rsg_pool.write_text(pool_source,encoding='utf-8',newline='\r\n')
    inventory=json.loads((OUT/'inventory.json').read_text(encoding='utf-8'))
    mods={m['id']:m for m in inventory['mods']}
    collection=json.loads(COLLECTION_REPORT.read_text(encoding='utf-8'))
    if collection.get('collection_id') != policy['collection_id']:
        raise RuntimeError('Resolved Steam collection does not match Phase A policy')
    missing_collection=[item['id'] for item in collection['items'] if item['id'] not in mods]
    collection_titles={item['id']:item.get('title') for item in collection['items']}
    if missing_collection:
        raise RuntimeError('Collection items are not installed locally: '+', '.join(missing_collection))

    active_bodies=set(pool['vanilla']+pool['required_custom']+pool['optional_custom'])
    planet_catalog=set(policy['planet_catalog_workshop'])
    non_catalog_planets=set(policy['non_catalog_planet_definition_mods'])
    detected_planet_catalog=set(planet_catalog)
    compatibility_policy=policy['compatibility_exclusions']
    selected=[]; selected_source={}; phase_planet_exclusions=[]; compatibility_exclusions=[]
    for item in collection['items']:
        id=item['id']; mod=mods[id]
        if id in compatibility_policy:
            compatibility_exclusions.append({'id':id,'title':item.get('title') or mod.get('title'),
                                             'reason':compatibility_policy[id]})
            continue
        is_planet_catalog=id in planet_catalog or (bool(mod['planets']) and id not in non_catalog_planets)
        if is_planet_catalog:
            detected_planet_catalog.add(id)
            subtypes=sorted({entry['subtype'] for entry in mod['planets']})
            selected_subtypes=sorted(set(subtypes)&active_bodies)
            if not selected_subtypes:
                phase_planet_exclusions.append({
                    'id':id,'title':item.get('title') or mod.get('title'),'planets':subtypes,
                    'desired':True,'active':False,
                    'reason':'planet catalog item excluded from Phase A active pool / voxel budget',
                })
                continue
            selected_source[id]={'source':'collection','classification':'phase_a_planet',
                                 'planets':selected_subtypes}
        else:
            selected_source[id]={'source':'collection','classification':'normal_collection_mod'}
        selected.append(id)

    support_additions=[]
    for id,reason in policy['required_support_workshop'].items():
        if id not in mods:
            raise RuntimeError('Required RSG support mod is not installed: '+id)
        if id not in selected:
            selected.append(id)
            selected_source[id]={'source':'rsg_support','classification':'required_support'}
            support_additions.append({'id':id,'title':mods[id]['title'] or collection_titles.get(id),
                                      'reason':reason})

    dependency_additions=[]
    dependency_index=0
    while dependency_index < len(selected):
        owner=selected[dependency_index]; dependency_index+=1
        for dependency in mods[owner].get('dependencies',[]):
            if dependency in selected: continue
            if dependency in compatibility_policy:
                raise RuntimeError('Selected mod '+owner+' requires blocked dependency '+dependency)
            if dependency not in mods:
                raise RuntimeError('Selected mod '+owner+' requires missing dependency '+dependency)
            selected.append(dependency)
            selected_source[dependency]={'source':'dependency','classification':'required_dependency'}
            dependency_additions.append({'id':dependency,'title':mods[dependency]['title'] or collection_titles.get(dependency),
                                         'required_by':owner})

    active_collection=set(selected)&{item['id'] for item in collection['items']}
    phase_by_id={item['id']:item for item in phase_planet_exclusions}
    compatibility_by_id={item['id']:item for item in compatibility_exclusions}
    for item in collection['items']:
        id=item['id']; item['active']=id in active_collection
        if id in phase_by_id:
            item['classification']='phase_a_planet_deferred'
            item['exclusion_reason']=phase_by_id[id]['reason']
        elif id in compatibility_by_id:
            item['classification']='compatibility_exclusion'
            item['exclusion_reason']=compatibility_by_id[id]['reason']
        else:
            item['classification']=selected_source[id]['classification']
            item['exclusion_reason']=None
    collection['missing_collection_items']=missing_collection
    COLLECTION_REPORT.write_text(json.dumps(collection,indent=2,ensure_ascii=False),
                                 encoding='utf-8',newline='\r\n')
    base={d['subtype'] for g in inventory['games'] for d in g['definitions']['voxels']}
    union=set(base); contributions=[]; owners=collections.defaultdict(list)
    for g in inventory['games']:
        for d in g['definitions']['voxels']:owners[d['subtype']].append(dict(mod='vanilla',**d))
    for id in selected:
        m=mods[id]; names={d['subtype'] for d in m['voxels']}
        contributions.append({'id':id,'title':m['title'] or collection_titles.get(id),
                              'count':len(names),'nonvanilla':sorted(names-base),'incremental':len(names-union)})
        union.update(names)
        for d in m['voxels']: owners[d['subtype']].append(dict(mod=id,**d))
    assert len(union)<=120, f'Unsafe selected pack: {len(union)}'
    vox={'vanilla':len(base),'total':len(union),'headroom':128-len(union),'budget':120,'per_mod':contributions,
         'duplicates':{k:v for k,v in owners.items() if len(v)>1},'subtypes':sorted(union),
         'qualification':'Static local SBC union; runtime definition mutations, dependency expansion, load precedence and engine indexing still require in-game verification.'}
    dump('selected-voxel-audit.json',vox)
    local=['RandomSectorGenerator','CampaignScienceCompatibility']
    generated_proxy=ROOT/'generated/CampaignPlanetProxies'
    if (generated_proxy/'Data/PlanetProxyDefaults.sbc').is_file():
        local.append('CampaignPlanetProxies')
    plan={'collection_id':policy['collection_id'],
          'collection_items':collection['items'],
          'selected_workshop':[{'id':i,'title':mods[i]['title'] or collection_titles.get(i) or TITLES.get(i),
                                'path':mods[i]['path'],**selected_source[i]} for i in selected],
          'dependency_additions':dependency_additions,
          'support_additions':support_additions,
          'phase_a_planet_exclusions':phase_planet_exclusions,
          'compatibility_exclusions':compatibility_exclusions,
          'missing_collection_items':missing_collection,
          'local':local}
    dump('pack-plan.json',plan)
    # Read native presets; exact names matter for variants.
    native={}
    for f in (Path(mods['3665099597']['path'])/'Data').glob('*.sbc'):
        for el in ET.parse(f).findall('.//EntityComponent'):
            sub=el.findtext('Id/SubtypeId','')
            if sub.startswith('PlanetBiomePresetType_'):native[sub.removeprefix('PlanetBiomePresetType_')]=str(f)
    # Authored matching rules; only identifiers and public schema are referenced.
    presets={
        'Cauldron':[('Northern Furnace',50,'Latitude: (0.6, 1)'),('Southern Furnace',50,'Latitude: (-1, -0.6)'),('Equatorial Furnace',40,'Latitude: (-0.2, 0.2)'),('Mantle Expanse',30,'Ores: Cauldron')],
        'Relicta':[('Polar Survey',40,'Latitude: (0.8, 1)'),('Southern Survey',40,'Latitude: (-1, -0.8)'),('Magma Fields',60,'Ores: RelMagma'),('Basalt Fields',35,'Ores: RelBasalt'),('Ancient Bedrock',35,'Ores: RelBedrock'),('Rocky Highlands',30,'Ores: RelRock')],
        'Jormun':[('River Lowlands',45,'Ores: Moss, MossFlowers, StoneMoss, Coral, CoralGrass'),('Dry Highlands',40,'Ores: StoneDesert, AlienSandGrass, StoneWhite'),('Rocky Ridges',35,'Ores: GrassStone1, GrassRock2, GrassRock3, GrassRock4')],
        'Zenitaia':[('Northern Survey',40,'Latitude: (0.8, 1)'),('Southern Survey',40,'Latitude: (-1, -0.8)'),('Grasslands',30,'Ores: Zenit_Grass'),('Ocean Sands',35,'Ores: Zenit_OCSand'),('Volcanic Gravel',40,'Ores: ZenitLavaGravel'),('Hot Rock Fields',55,'Ores: ZenitHotRock, ZenitLavaRockOC, ZenitLavaRockSurface')],
        'Kerbin - Water Mod Ready':[('Coastal Survey',35,'Ores: Sand_02, MoonSoil, MoonRocks'),('Temperate Highlands',35,'Ores: Soil, Grass, Woods_grass'),('Polar Cap',45,'Ores: Snow, TritonIce')],
        'Aulden':[('Frost Fields',45,'Ores: Snow, Ice_03, TritonIce'),('Wooded Basin',35,'Ores: Woods_grass, Grass, Soil'),('Stone Ridges',40,'Ores: Stone_01, Rocks_grass, TritonStone')]
    }
    xsi='http://www.w3.org/2001/XMLSchema-instance'; ET.register_namespace('xsi',xsi)
    root=ET.Element('Definitions'); components=ET.SubElement(root,'EntityComponents')
    for planet,biomes in presets.items():
        assert planet not in native
        el=ET.SubElement(components,'EntityComponent',{f'{{{xsi}}}type':'MyObjectBuilder_InventoryComponentDefinition'})
        ident=ET.SubElement(el,'Id'); ET.SubElement(ident,'TypeId').text='Inventory';ET.SubElement(ident,'SubtypeId').text='PlanetBiomePresetType_'+planet
        ET.SubElement(el,'Description').text='\nSlopeCheckDist: 100\n'+'\n'.join(f'Biome: {n}\nScienceReward: {r}\n{condition}\n' for n,r,condition in biomes)
    dest=ROOT/'mods/CampaignScienceCompatibility/Data';dest.mkdir(parents=True,exist_ok=True)
    ET.indent(root);ET.ElementTree(root).write(dest/'CampaignBiomes.sbc',encoding='utf-8',xml_declaration=True)
    proxy=collections.defaultdict(list)
    proxy_sources=list(mods.values())
    if (generated_proxy/'Data/PlanetProxyDefaults.sbc').is_file():
        local_scan=scan(generated_proxy)
        proxy_sources.append(dict(id='local:CampaignPlanetProxies',path=str(generated_proxy),**local_scan))
    for m in proxy_sources:
        for p in m['proxies']:
            names=[p['subtype'].removeprefix('PlanetProxyType_')]
            import re
            names+=re.findall(r'PlanetDefaults:\s*([^\n\r]+)',p.get('description') or '')
            for name in [n.strip() for s in names for n in s.split(',')]:
                proxy[name].append(dict(mod=m['id'],root=m['path'],**p))
    active_proxy_sources=set(selected)
    if 'CampaignPlanetProxies' in local:
        active_proxy_sources.add('local:CampaignPlanetProxies')
    coverage=[]
    coverage_ids=[id for id in policy['planet_catalog_workshop'] if id in mods]
    coverage_ids += [item['id'] for item in collection['items']
                     if item['id'] in detected_planet_catalog and item['id'] not in coverage_ids]
    coverage_sources=[(id,mods[id]['title'] or collection_titles.get(id) or TITLES.get(id) or id)
                      for id in coverage_ids]
    for id,title in coverage_sources:
        for p in mods.get(id,{}).get('planets',[{'subtype':'unavailable'}]):
            name=p['subtype']; candidates=proxy.get(name,[])
            chosen=[c for c in candidates if c['mod'] in active_proxy_sources]
            is_selected=id in selected and name in active_bodies
            coverage.append({'id':id,'planet':name,'selected':is_selected,'proxy_candidates':candidates,'active_proxy_count':len(chosen),
                             'science_native':native.get(name),'science_compatibility':name in presets,
                             'science_status':'native' if name in native else 'local authored preset' if name in presets else 'unavailable' if name=='unavailable' else 'generic fallback'})
    for name in pool['vanilla']:
        candidates=proxy.get(name,[])
        coverage.append({'id':'vanilla','planet':name,'selected':True,'proxy_candidates':candidates,
                         'active_proxy_count':sum(c['mod'] in active_proxy_sources for c in candidates),
                         'science_native':native.get(name),'science_compatibility':False,
                         'science_status':'native' if name in native else 'missing'})
    dump('coverage.json',coverage)
    # Keep the workbench target list reproducible after the generated local mod
    # is built; local output is not an alternate source for a fresh export.
    export_targets=[c['planet'] for c in coverage if c['selected'] and c['planet']!='Jormun'
                    and not any(p['mod'] in selected for p in c['proxy_candidates'])]
    helper_source=ROOT/'mods/ProxyExportBootstrap/Data/Scripts/ProxyExportBootstrap/ProxyExportTargets.cs'
    source='''// Generated by scripts/prepare_pack.py from the selected proxy coverage.\nnamespace ProxyExportBootstrap\n{\n    internal static class ProxyExportTargets\n    {\n        internal static readonly string[] Names = new string[]\n        {\n'''
    source+=''.join('            '+json.dumps(name)+',\n' for name in export_targets)
    source+='''        };\n    }\n}\n'''
    helper_bytes=source.replace('\n','\r\n').encode('utf-8')
    if not helper_source.is_file() or helper_source.read_bytes()!=helper_bytes:
        helper_source.write_text(source,encoding='utf-8',newline='\r\n')
    dump('planet-cut-options.json',{
        'phase_a_fixed_pool':sorted(active_bodies),
        'deferred_collection_planets':phase_planet_exclusions,
        'note':'Phase A uses the fixed 18-body pool; randomized subset selection is deferred to Phase B.',
    })
    selected_bodies=[c for c in coverage if c['selected']]
    normal_active=sum(item['active'] and item['classification']=='normal_collection_mod'
                      for item in collection['items'])
    planet_active=sum(item['active'] and item['classification']=='phase_a_planet'
                      for item in collection['items'])
    lines=['# Selected pack audit','',
           f'Steam collection: **{policy["collection_id"]}** ({len(collection["items"])} current children; '+
           ('cached snapshot explicitly selected).' if collection.get('cache_used') else 'resolved live from Steam.'),
           f'Active Workshop mods: **{len(selected)}** ({normal_active} normal collection mods, {planet_active} Phase A planet mods, {len(dependency_additions)} dependency additions).',
           '',f'Selected planet definitions: **{len(selected_bodies)}** ({len(pool["vanilla"])} vanilla, {len(selected_bodies)-len(pool["vanilla"])} custom).',
           '',f'Static voxel total: **{len(union)}** = {len(base)} vanilla + {len(union-base)} additions; **{128-len(union)}** headroom against 128 and {120-len(union)} below the conservative budget of 120. Expanded-pool runtime validation pending.','',
           '| Body | Selected | Active RSS proxies | Science |','|---|---|---:|---|']
    lines += [f"| {c['planet']} | {'yes' if c['selected'] else 'no'} | {c['active_proxy_count']} | {c['science_status']} |" for c in coverage]
    lines+=['','## Collection exclusions','',
            *['- '+entry['id']+' — '+str(entry['title'])+': '+entry['reason'] for entry in phase_planet_exclusions+compatibility_exclusions],
            '', '## Workshop load-list membership','',*['- '+i+' — '+str(mods[i]['title'] or collection_titles.get(i) or TITLES.get(i) or 'title unavailable locally') for i in selected],
            '', '## Local mods', '', *[
                '- '+name+(
                    ': one-shot Random Sector bootstrap, direct persisted RSS handoff, spoiler manifest.' if name=='RandomSectorGenerator'
                    else ': authored Cauldron, Jormun, Relicta, Zenitaia, Kerbin, and Aulden biome presets.' if name=='CampaignScienceCompatibility'
                    else ': generated RSS proxy definitions/assets for campaign planets.'
                )
                for name in local
            ],
            '', '## Water and encounters', '',
            'Jormun and Zenitaia remain the verified intended water worlds. The selected Kerbin subtype uses water-ready terrain, but actual Water Mod behavior needs a runtime check. No global water entry is added to other planets.',
            'MES, Assertive Combat Systems, Abandoned Settlements, and AiEnabled are retained. MES warns about NPC grid precision beyond 6,500 km from origin; RSS clamps its physical voxel spawn range to at least 10,000 km. No confirmed safe configuration-only repair was found. Planetary NPC spawning near RSS physical planets remains an acceptance risk.',
            '', '## Limits', '',
            'The collection is the desired catalog. Phase A keeps its fixed 18-body pool; other catalog planets remain installed and are reported as inactive instead of being silently enabled.',
            'RSS itself provides exactly one proxy for every vanilla planet; the installed vanilla HD pack is excluded to prevent duplicates. Cauldron bundles four exact proxies, Orlunda Sideways uses its SD pack, and the generated local proxy mod supplies Jormun and the remaining exported proxies. Selected static coverage is '+str(sum(c['active_proxy_count']==1 for c in selected_bodies))+'/'+str(len(selected_bodies))+'.',
            'No old-save Workshop membership participates in selection. Unique subtype union is independent of override precedence.',
            'The most recent pre-change game log loaded 189 unique voxel materials from the old pack. The new pack has passed static auditing and offline RSG compilation, but has not been launched, generated, reloaded, or checked for water/science/MES behavior in game.']
    (OUT/'PACK-AUDIT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\r\n')
    print(f'Selected {len(selected)} Workshop mods, voxel total {len(union)}; missing selected proxies: '+', '.join(c['planet'] for c in coverage if c['selected'] and not c['active_proxy_count']))

if __name__=='__main__':main()
