"""Derive the selected pack and original science presets from audited local definitions."""
import json, itertools, collections, xml.etree.ElementTree as ET
from pathlib import Path
from audit import ROOT, OUT, ALLOW, DENY, dump, scan

CUTS = {'2195637331','2644430625','3309805284','3486181518','3515518898','3684013414'}
EXTRA = {'3690317665':'AquaExpansion', '2899106264':'Terran Titans Naval Blocks'}
TITLES = {'2941085186':'Kerbin', '2961923776':'Aulden', '2961924256':'Seren'}
PROXY_PACKS = {
    '3361803398':'RSS Proxy Pack: Orlunda and Komorebi (SD)',
}
PROXY_ASSET_SOURCES = {
    '3663505475':'Planet Jormun proxy texture source',
}
EXPORTER = '3350589349'

def main():
    pool=json.loads((ROOT/'campaign-planets.json').read_text(encoding='utf-8'))
    rsg_pool=ROOT/'mods/RandomSectorGenerator/Data/Scripts/RandomSectorGenerator/CampaignPlanetPool.cs'
    pool_source='// Generated by scripts/prepare_pack.py from campaign-planets.json.\nnamespace RandomSectorGenerator\n{\n    internal static class CampaignPlanetPool\n    {\n'
    for field,key in [('RequiredCustom','required_custom'),('Vanilla','vanilla'),('OptionalCustom','optional_custom')]:
        pool_source+='        internal static readonly string[] '+field+' = new string[]\n        {\n'
        pool_source+=''.join('            '+json.dumps(name)+',\n' for name in pool[key])
        pool_source+='        };\n'
    pool_source+='    }\n}\n'
    if not rsg_pool.is_file() or rsg_pool.read_text(encoding='utf-8')!=pool_source:
        rsg_pool.write_text(pool_source,encoding='utf-8')
    inventory=json.loads((OUT/'inventory.json').read_text(encoding='utf-8'))
    mods={m['id']:m for m in inventory['mods']}
    original=[m['PublishedFileId'] for m in inventory['worlds'][0]['mods']]
    selected=[i for i in original if i in mods and i not in DENY and i not in CUTS]
    for i in list(ALLOW)+list(EXTRA):
        if i in mods and i not in CUTS and i not in selected: selected.append(i)
    for i in pool['additional_workshop']:
        if i not in mods:
            raise RuntimeError('Selected planet Workshop mod is not installed: '+i)
        if i not in selected: selected.append(i)
    # Select only the audited SD proxy packs required by the retained planets.
    # Never add HD duplicates alongside these.
    for i in PROXY_PACKS:
        if i in mods and i not in selected:
            selected.append(i)
    base={d['subtype'] for g in inventory['games'] for d in g['definitions']['voxels']}
    union=set(base); contributions=[]; owners=collections.defaultdict(list)
    for g in inventory['games']:
        for d in g['definitions']['voxels']:owners[d['subtype']].append(dict(mod='vanilla',**d))
    for id in selected:
        m=mods[id]; names={d['subtype'] for d in m['voxels']}
        contributions.append({'id':id,'title':m['title'] or EXTRA.get(id),'count':len(names),'nonvanilla':sorted(names-base),'incremental':len(names-union)})
        union.update(names)
        for d in m['voxels']: owners[d['subtype']].append(dict(mod=id,**d))
    assert len(union)<=120, f'Unsafe selected pack: {len(union)}'
    vox={'vanilla':len(base),'total':len(union),'headroom':128-len(union),'budget':120,'per_mod':contributions,
         'duplicates':{k:v for k,v in owners.items() if len(v)>1},'subtypes':sorted(union),
         'qualification':'Static local SBC union; runtime definition mutations, dependency expansion, load precedence and engine indexing still require in-game verification.'}
    dump('selected-voxel-audit.json',vox)
    local=['RandomSectorGenerator','CampaignScienceCompatibility']
    generated_proxy=ROOT/'generated/CampaignPlanetProxies'
    if (generated_proxy/'Data/PlanetProxyDefaults.sbc').is_file():
        local.append('CampaignPlanetProxies')
    plan={'selected_workshop':[{'id':i,'title':mods[i]['title'] or EXTRA.get(i) or TITLES.get(i),'path':mods[i]['path']} for i in selected],
          'local':local,
          'cut_for_budget':sorted(CUTS),'missing_requested':[i for i in ALLOW if i not in mods],
          'stale_missing_world_entries':[i for i in original if i not in mods],
          'denylisted_installed':[i for i in DENY if i in mods],
          'proxy_download_required':[i for i in PROXY_PACKS if i not in mods],
          'proxy_pack_ids':list(PROXY_PACKS),
          'proxy_asset_source_required':[i for i in PROXY_ASSET_SOURCES if i not in mods],
          'proxy_asset_source_ids':list(PROXY_ASSET_SOURCES),
          'exporter_download_required':[] if EXPORTER in mods else [EXPORTER]}
    dump('pack-plan.json',plan)
    # Read native presets; exact names matter for variants.
    native={}
    for f in (Path(mods['3665099597']['path'])/'Data').glob('*.sbc'):
        for el in ET.parse(f).findall('.//EntityComponent'):
            sub=el.findtext('Id/SubtypeId','')
            if sub.startswith('PlanetBiomePresetType_'):native[sub.removeprefix('PlanetBiomePresetType_')]=str(f)
    # Authored matching rules; only identifiers and public schema are referenced.
    presets={
        'Cauldron':[('Northern Furnace',50,'Latitude: (0.6, 1)'),('Southern Furnace',50,'Latitude: (-1, -0.6)'),('Equatorial Furnace',40,'Latitude: (-0.2, 0.2)'),('Mantle Expanse',30,'Ores: Cauldron')],
        'Relicta':[('Polar Survey',40,'Latitude: (0.8, 1)'),('Southern Survey',40,'Latitude: (-1, -0.8)'),('Magma Fields',60,'Ores: RelMagma'),('Basalt Fields',35,'Ores: RelBasalt'),('Ancient Bedrock',35,'Ores: RelBedrock'),('Rocky Highlands',30,'Ores: RelRock')],
        'Jormun':[('River Lowlands',45,'Ores: Moss, MossFlowers, StoneMoss, Coral, CoralGrass'),('Dry Highlands',40,'Ores: StoneDesert, AlienSandGrass, StoneWhite'),('Rocky Ridges',35,'Ores: GrassStone1, GrassRock2, GrassRock3, GrassRock4')],
        'Zenitaia':[('Northern Survey',40,'Latitude: (0.8, 1)'),('Southern Survey',40,'Latitude: (-1, -0.8)'),('Grasslands',30,'Ores: Zenit_Grass'),('Ocean Sands',35,'Ores: Zenit_OCSand'),('Volcanic Gravel',40,'Ores: ZenitLavaGravel'),('Hot Rock Fields',55,'Ores: ZenitHotRock, ZenitLavaRockOC, ZenitLavaRockSurface')],
        'Kerbin - Water Mod Ready':[('Coastal Survey',35,'Ores: Sand_02, MoonSoil, MoonRocks'),('Temperate Highlands',35,'Ores: Soil, Grass, Woods_grass'),('Polar Cap',45,'Ores: Snow, TritonIce')],
        'Aulden':[('Frost Fields',45,'Ores: Snow, Ice_03, TritonIce'),('Wooded Basin',35,'Ores: Woods_grass, Grass, Soil'),('Stone Ridges',40,'Ores: Stone_01, Rocks_grass, TritonStone')],
        'Seren':[('Frozen Expanse',50,'Ores: Ice_03'),('High Gravity Traverse',60,'Latitude: (-0.7, 0.7)')]
    }
    xsi='http://www.w3.org/2001/XMLSchema-instance'; ET.register_namespace('xsi',xsi)
    root=ET.Element('Definitions'); components=ET.SubElement(root,'EntityComponents')
    for planet,biomes in presets.items():
        assert planet not in native
        el=ET.SubElement(components,'EntityComponent',{f'{{{xsi}}}type':'MyObjectBuilder_InventoryComponentDefinition'})
        ident=ET.SubElement(el,'Id'); ET.SubElement(ident,'TypeId').text='Inventory';ET.SubElement(ident,'SubtypeId').text='PlanetBiomePresetType_'+planet
        ET.SubElement(el,'Description').text='\nSlopeCheckDist: 100\n'+'\n'.join(f'Biome: {n}\nScienceReward: {r}\n{condition}\n' for n,r,condition in biomes)
    dest=ROOT/'mods/CampaignScienceCompatibility/Data';dest.mkdir(parents=True,exist_ok=True)
    ET.indent(root);ET.ElementTree(root).write(dest/'CampaignBiomes.sbc',encoding='utf-8',xml_declaration=True)
    proxy=collections.defaultdict(list)
    proxy_sources=list(mods.values())
    if (generated_proxy/'Data/PlanetProxyDefaults.sbc').is_file():
        local_scan=scan(generated_proxy)
        proxy_sources.append(dict(id='local:CampaignPlanetProxies',path=str(generated_proxy),**local_scan))
    for m in proxy_sources:
        for p in m['proxies']:
            names=[p['subtype'].removeprefix('PlanetProxyType_')]
            import re
            names+=re.findall(r'PlanetDefaults:\s*([^\n\r]+)',p.get('description') or '')
            for name in [n.strip() for s in names for n in s.split(',')]:
                proxy[name].append(dict(mod=m['id'],root=m['path'],**p))
    active_proxy_sources=set(selected)
    if 'CampaignPlanetProxies' in local:
        active_proxy_sources.add('local:CampaignPlanetProxies')
    coverage=[]
    coverage_sources=list(ALLOW.items())+[(i,'Phase 2A candidate') for i in pool['additional_workshop']]
    for id,title in coverage_sources:
        for p in mods.get(id,{}).get('planets',[{'subtype':'unavailable'}]):
            name=p['subtype']; candidates=proxy.get(name,[])
            chosen=[c for c in candidates if c['mod'] in active_proxy_sources]
            is_selected=id in selected and (id not in pool['additional_workshop'] or name in pool['additional_workshop'][id])
            coverage.append({'id':id,'planet':name,'selected':is_selected,'proxy_candidates':candidates,'active_proxy_count':len(chosen),
                             'science_native':native.get(name),'science_compatibility':name in presets,
                             'science_status':'native' if name in native else 'local authored preset' if name in presets else 'unavailable' if name=='unavailable' else 'generic fallback'})
    for name in pool['vanilla']:
        candidates=proxy.get(name,[])
        coverage.append({'id':'vanilla','planet':name,'selected':True,'proxy_candidates':candidates,
                         'active_proxy_count':sum(c['mod'] in active_proxy_sources for c in candidates),
                         'science_native':native.get(name),'science_compatibility':False,
                         'science_status':'native' if name in native else 'missing'})
    dump('coverage.json',coverage)
    export_targets=[c['planet'] for c in coverage if c['selected'] and c['active_proxy_count']==0]
    helper_source=ROOT/'mods/ProxyExportBootstrap/Data/Scripts/ProxyExportBootstrap/ProxyExportTargets.cs'
    source='''// Generated by scripts/prepare_pack.py from the selected proxy coverage.\nnamespace ProxyExportBootstrap\n{\n    internal static class ProxyExportTargets\n    {\n        internal static readonly string[] Names = new string[]\n        {\n'''
    source+=''.join('            '+json.dumps(name)+',\n' for name in export_targets)
    source+='''        };\n    }\n}\n'''
    if not helper_source.is_file() or helper_source.read_text(encoding='utf-8')!=source:
        helper_source.write_text(source,encoding='utf-8')
    # Compute all minimum-cardinality cuts, including alternatives retaining Cauldron.
    planets=[m for m in mods.values() if m['desired_planet']]
    alternatives={}
    required_base=set(base)
    for id in EXTRA:
        if id in mods: required_base.update(d['subtype'] for d in mods[id]['voxels'])
    for label,protected in [('unconstrained',set()),('preserve_cauldron',{'3576683005'}),('preserve_cauldron_and_selected_water',{'3576683005','2644430625','2195637331','3695766186'})]:
        for count in range(len(planets)+1):
            options=[]
            for cut in itertools.combinations([m for m in planets if m['id'] not in protected],count):
                ids={m['id'] for m in cut}; names=set(required_base)
                for m in planets:
                    if m['id'] not in ids:names.update(d['subtype'] for d in m['voxels'])
                if len(names)<=120:options.append({'cut':sorted(ids),'total':len(names)})
            if options:alternatives[label]={'minimum_mod_cuts':count,'options':options};break
    dump('planet-cut-options.json',alternatives)
    selected_bodies=[c for c in coverage if c['selected']]
    lines=['# Selected pack audit','',f'Selected planet definitions: **{len(selected_bodies)} / 24** ({len(pool["vanilla"])} vanilla, {len(selected_bodies)-len(pool["vanilla"])} custom).',
           '',f'Static voxel total: **{len(union)}** = {len(base)} vanilla + {len(union-base)} additions; **{128-len(union)}** headroom against 128 and {120-len(union)} below the conservative budget of 120. Expanded-pool runtime validation pending.','',
           '| Body | Selected | Active RSS proxies | Science |','|---|---|---:|---|']
    lines += [f"| {c['planet']} | {'yes' if c['selected'] else 'no'} | {c['active_proxy_count']} | {c['science_status']} |" for c in coverage]
    lines+=['','## Workshop load-list membership','',*['- '+i+' — '+str(mods[i]['title'] or EXTRA.get(i) or TITLES.get(i) or 'title unavailable locally') for i in selected],
            '', '## Local mods', '', *[
                '- '+name+(
                    ': one-shot armed disposable-world bootstrap, pending RSS checkpoint handoff, spoiler manifest.' if name=='RandomSectorGenerator'
                    else ': authored Cauldron, Jormun, Relicta, Zenitaia, Kerbin, Aulden, and Seren biome presets.' if name=='CampaignScienceCompatibility'
                    else ': generated RSS proxy definitions/assets for campaign planets.'
                )
                for name in local
            ],
            '', '## Water and encounters', '',
            'Jormun and Zenitaia remain the verified intended water worlds. The selected Kerbin subtype uses water-ready terrain, but actual Water Mod behavior needs a runtime check. No global water entry is added to other planets.',
            'MES, Assertive Combat Systems, Abandoned Settlements, and AiEnabled are retained. MES warns about NPC grid precision beyond 6,500 km from origin; RSS clamps its physical voxel spawn range to at least 10,000 km. No confirmed safe configuration-only repair was found. Planetary NPC spawning near RSS physical planets remains an acceptance risk.',
            '', '## Limits', '',
            'Phase 2A adds all four omitted vanilla planets plus the verified zero-material Kerbin water variant, Aulden, and Seren. No installed distinct +1/+2 candidate was found. Teal, Teralis, Komorebi, Nivis, Sulfate, and Acribus remain excluded for the material budget.',
            'RSS itself provides exactly one proxy for every vanilla planet; the installed vanilla HD pack is excluded to prevent duplicates. Cauldron bundles four exact proxies, Orlunda Sideways uses its SD pack, and Jormun uses its dedicated source. Zenitaia, Relicta, Kerbin, Aulden, and Seren require one batch export. The campaign world remains disarmed until coverage is exact.',
            'Voxel modifiers are excluded. No subtype duplicates were found in the selected local definitions. Unique subtype union is independent of override precedence. The old test save contained stale Workshop entries and was not edited; its static voxel estimate is a lower bound. The original was preserved in timestamped ZIPs.',
            'The most recent pre-change game log loaded 189 unique voxel materials from the old pack. The new pack has passed static auditing and offline RSG compilation, but has not been launched, generated, reloaded, or checked for water/science/MES behavior in game.']
    (OUT/'PACK-AUDIT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(f'Selected {len(selected)} Workshop mods, voxel total {len(union)}; missing selected proxies: '+', '.join(c['planet'] for c in coverage if c['selected'] and not c['active_proxy_count']))

if __name__=='__main__':main()
