// Generated by scripts/prepare_pack.py from campaign-planets.json.
namespace RandomSectorGenerator
{
    internal static class CampaignPlanetPool
    {
        internal static readonly string[] RequiredCustom = new string[]
        {
            "Cauldron",
            "Tellus",
            "Agni",
            "Kor",
            "Jormun",
            "Zenitaia",
            "OrlundaSide",
            "Relicta",
        };
        internal static readonly string[] Vanilla = new string[]
        {
            "EarthLike",
            "Moon",
            "Mars",
            "Europa",
            "Alien",
            "Titan",
            "Triton",
            "Pertam",
        };
        internal static readonly string[] OptionalCustom = new string[]
        {
            "Kerbin - Water Mod Ready",
            "Aulden",
            "Seren",
        };
    }
}
